let name = "Justin"
console.log(name[3])
console.log(name.length)
console.log(name[name.length-1])
console.log(name.indexOf("u"))
console.log(name.indexOf("p"))
console.log(name.concat(" Kilburn"))
console.log(name)
name = name.concat(" Kilburn")
console.log(name)
// anything at all
console.log(10+3)
console.log(10-3)
console.log(10*3)
console.log(10/3)
console.log(10%3)
console.log(10%2)
console.log(2%5)
console.log(true||false&&false)
console.log(true&&false)